version: "3.9"

services:
  mysql:
    image: mysql:latest
    container_name: my-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=finance
      - MYSQL_DATABASE=finances
      - MYSQL_USER=finance
      - MYSQL_PASSWORD=finance
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
