version: "3.9"

services:
  mariadb:
    image: mariadb:latest
    container_name: my-mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=finance
      - MYSQL_DATABASE=finances
      - MYSQL_USER=finance
      - MYSQL_PASSWORD=finance
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
